### ISSUE TITLE
Applying compiler patch to 4.01.0

### ISSUE THREAD

**Issue by andrewray** [OCamlPro/tryocaml#141]
I would like to try recompiling ocaml 4.01.0 with the pa_js syntax patch.  The reason is I need access to a few more .cmi files to compile [iocamljs](https://github.com/andrewray/iocamljs).

I have tried applying with `patch -pX` but it complains about garbage.

Looking about for something related to `diff --combined` which appears at the top of the patch the nearest I could come up with is some sort of git pacth, so I tried `git apply` but it's not happy either failing with `unrecognized input`.  I'm stuck now - how do you apply this patch?

Cheers,
Andy

**Comment by hhugo** [comment]
I believe this can be closed.
